#
# Module manifest for module 'PsUi'
#
# Generated by: Jacob Labonte
#
# Updated: 2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\PsUi.psm1'

# Version number of this module.
ModuleVersion = '1.0.2'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '205560a1-3780-4ce1-9ff3-480141781fe4'

# Author of this module
Author = 'Jacob Labonte'

# Company or vendor of this module
CompanyName = 'Jacob Labonte'

# Copyright statement for this module
Copyright = '(c) 2026 Jacob Labonte. All rights reserved.'

# What this module does
Description = 'WPF toolkit for PowerShell. DSL-based controls, async execution, theming. No XAML.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
# Only public functions are exported. Private functions are injected into async runspaces via ModuleContext.
FunctionsToExport = @(
    'Add-UiListItem'
    'Clear-UiList'
    'Get-PsUiIcon'
    'Get-PsUiIconList'
    'Get-UiListItems'
    'Get-UiThemeTemplate'
    'Get-UiValue'
    'Invoke-UiAsync'
    'New-UiAction'
    'New-UiActionCard'
    'New-UiButton'
    'New-UiButtonCard'
    'New-UiCard'
    'New-UiChart'
    'New-UiChildWindow'
    'New-UiCredential'
    'New-UiDatePicker'
    'New-UiDropdown'
    'New-UiDropdownButton'
    'New-UiExpander'
    'New-UiGlyph'
    'New-UiGrid'
    'New-UiImage'
    'New-UiInput'
    'New-UiLabel'
    'New-UiLink'
    'New-UiList'
    'New-UiPanel'
    'New-UiProgress'
    'New-UiRadioGroup'
    'New-UiSeparator'
    'New-UiSlider'
    'New-UiTab'
    'New-UiTextArea'
    'New-UiTimePicker'
    'New-UiToggle'
    'New-UiTool'
    'New-UiTree'
    'New-UiWebView'
    'Out-CSVDataGrid'
    'Out-Datagrid'
    'Out-TextEditor'
    'Register-UiHotkey'
    'Register-UiTheme'
    'Remove-UiListItem'
    'Reset-UiSession'
    'Set-UiProgress'
    'Set-UiValue'
    'Show-UiChoiceDialog'
    'Show-UiConfirmDialog'
    'Show-UiCredentialDialog'
    'Show-UiDialog'
    'Show-UiFilePicker'
    'Show-UiFolderPicker'
    'Show-UiGlyphBrowser'
    'Show-UiInputDialog'
    'Show-UiMessageDialog'
    'Show-UiPromptDialog'
    'Show-UiSaveDialog'
    'Show-WindowsObjectPicker'
    'Stop-UiAsync'
    'Update-UiChart'
    'Write-UiHostDirect'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'New-UiWindow'
)

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('GUI', 'Windows', 'Forms', 'Menu', 'Dialog', 'DataGrid', 'WPF', 'DSL')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/jlabon2/PsUi/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/jlabon2/PsUi'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.0.1:
- New-UiButton: -ScrollToTop switch for controlling post-completion scroll position
- New-UiTool: Detect missing help files in PS 7+, offer online docs fallback
- Show-UiFilterBuilder: Fix combobox vertical centering
- CI: Add Pester test workflow
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
