# Store themes in ModuleContext for cross-runspace access
[PsUi.ModuleContext]::Themes = @{
    # Standard Dark: Deep gray/gunmetal (easier on eyes than pure black)
    Dark = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#202020'
        WindowFg = '#E0E0E0'
        ControlBg = '#2D2D2D'
        ControlFg = '#E0E0E0'
        ButtonBg = '#383838'
        ButtonFg = '#FFFFFF'
        ButtonHover = '#454545'
        Border = '#404040'
        GroupBoxBg = '#252525'
        GroupBoxBorder = '#3A3A3A'
        Accent = '#78B802'
        HeaderBackground = '#1A1A1A'
        HeaderForeground = '#FFFFFF'
        AccentHeaderBg = '#78B802'
        AccentHeaderFg = '#202020'
        Success = '#6CCB5F'
        Warning = '#FCE100'
        Error = '#FF99A4'
        GridAlt = '#252525'
        GridLine = '#3A3A3A'          # Subtle grid line separator
        Disabled = '#707070'
        SecondaryText = '#A0A0A0'
        ItemHover = '#3A3A3A'         # Subtle gray hover
        Selection = '#78B802'         # Accent = Selection
        SelectionBackground = '#9DD035'  # Lighter green for dark theme
        SelectionFg = '#1A1A1A'
        FindHighlight = '#4CC2FF'
        TextHighlight = '#78B802'     # Text selection highlight (accent-based)
        TextHighlightFg = '#FFFFFF'
        SelectedTabBg = '#383838'
        TabHoverBg = '#383838'
        ErrorText = '#F08080'
        WarningText = '#FFB366'
        SuccessText = '#90EE90'
        SelectionTextBrush = '#000000'
        Link = '#FFFFFF'
    }

    # Light: Clean professional light theme
    Light = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#FAFAFA'
        WindowFg = '#383A42'
        ControlBg = '#FFFFFF'
        ControlFg = '#383A42'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#383A42'
        ButtonHover = '#EAEAEB'
        Border = '#D3D3D4'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#E5E5E6'
        Accent = '#4078F2'
        HeaderBackground = '#EAEAEB'
        HeaderForeground = '#383A42'
        AccentHeaderBg = '#4078F2'
        AccentHeaderFg = '#FFFFFF'
        Success = '#50A14F'
        Warning = '#C18401'
        Error = '#E45649'
        GridAlt = '#F5F5F5'           # Alternating row - subtle contrast from #FAFAFA
        GridLine = '#E0E0E0'          # Subtle grid line separator
        Disabled = '#A0A1A7'
        SecondaryText = '#696C77'
        ItemHover = '#EDF2FC'         # Subtle blue hover
        Selection = '#4078F2'         # Accent = Selection
        SelectionBackground = '#3267D6'  # Darker blue for selection
        SelectionFg = '#FFFFFF'
        FindHighlight = '#E5C07B'
        TextHighlight = '#D5E4FC'     # Light blue text selection
        TextHighlightFg = '#2E4688'
        SelectedTabBg = '#E8EEFA'
        TabHoverBg = '#E8EEFA'
        ErrorText = '#E45649'
        WarningText = '#C18401'
        SuccessText = '#50A14F'
        SelectionTextBrush = '#FFFFFF'
        Link = '#4078F2'
    }

    # Blossom: Soft rose accents on warm cream, modern and calming
    'Blossom' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#FAF4ED'
        WindowFg = '#575279'
        ControlBg = '#FFFAF3'
        ControlFg = '#575279'
        ButtonBg = '#FFFAF3'
        ButtonFg = '#575279'
        ButtonHover = '#F2E9E1'
        Border = '#DFDAD9'
        GroupBoxBg = '#FFFAF3'
        GroupBoxBorder = '#F2E9DE'
        Accent = '#D7827E'            # Dusty rose
        HeaderBackground = '#F2E9E1'
        HeaderForeground = '#575279'
        AccentHeaderBg = '#D7827E'
        AccentHeaderFg = '#FFFAF3'
        Success = '#286983'
        Warning = '#EA9D34'
        Error = '#B4637A'
        GridAlt = '#F4EDE8'
        GridLine = '#E8DED8'          # Subtle grid line separator
        Disabled = '#9893A5'
        SecondaryText = '#797593'
        ItemHover = '#F4E8E8'         # Subtle rose hover
        Selection = '#D7827E'         # Accent = Selection
        SelectionBackground = '#C56D69'
        SelectionFg = '#FFFAF3'
        FindHighlight = '#EA9D34'
        TextHighlight = '#F4D6D4'     # Light rose text selection
        TextHighlightFg = '#6E4C4A'
        SelectedTabBg = '#F4E8E8'
        TabHoverBg = '#F4E8E8'
        ErrorText = '#B4637A'
        WarningText = '#EA9D34'
        SuccessText = '#286983'
        SelectionTextBrush = '#000000'
        Link = '#907AA9'
    }

    # Ember: Warm orange accent on clean white, inspired by Ayu Light
    'Ember' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#FAFAFA'
        WindowFg = '#5C6166'
        ControlBg = '#FFFFFF'
        ControlFg = '#5C6166'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#5C6166'
        ButtonHover = '#F0F0F0'
        Border = '#D8D8D8'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#E8E8E8'
        Accent = '#FF9940'            # Warm orange
        HeaderBackground = '#F0F0F0'
        HeaderForeground = '#5C6166'
        AccentHeaderBg = '#FF9940'
        AccentHeaderFg = '#FFFFFF'
        Success = '#6CBF43'
        Warning = '#F2AE49'
        Error = '#E65050'
        GridAlt = '#F5F5F5'           # Alternating row - subtle contrast
        GridLine = '#E0E0E0'          # Subtle grid line separator
        Disabled = '#ABB0B6'
        SecondaryText = '#787B80'
        ItemHover = '#FFF4E8'         # Subtle orange tint
        Selection = '#FF9940'
        SelectionBackground = '#E07A20'
        SelectionFg = '#FFFFFF'
        FindHighlight = '#F2AE49'
        TextHighlight = '#FFE6CC'     # Light orange selection
        TextHighlightFg = '#8B5A00'
        SelectedTabBg = '#FFEEDD'
        TabHoverBg = '#FFEEDD'
        ErrorText = '#E65050'
        WarningText = '#E09629'
        SuccessText = '#6CBF43'
        SelectionTextBrush = '#000000'
        Link = '#399EE6'
    }

    # Ocean Blue: Deep Navy and Slate
    'OceanBlue' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#0F172A'
        WindowFg = '#E2E8F0'
        ControlBg = '#1E293B'
        ControlFg = '#E2E8F0'
        ButtonBg = '#334155'
        ButtonFg = '#F8FAFC'
        ButtonHover = '#475569'
        Border = '#334155'
        GroupBoxBg = '#162032'
        GroupBoxBorder = '#2D3A4F'
        Accent = '#3B82F6'           # Bright blue
        HeaderBackground = '#0B1120'
        HeaderForeground = '#F8FAFC'
        AccentHeaderBg = '#FF7F50'
        AccentHeaderFg = '#0F172A'
        Success = '#34D399'
        Warning = '#FBBF24'
        Error = '#F87171'
        GridAlt = '#172033'
        GridLine = '#334155'          # Subtle grid line separator
        Disabled = '#64748B'
        SecondaryText = '#94A3B8'
        ItemHover = '#2D3A4F'         # Subtle hover
        Selection = '#3B82F6'         # Accent = Selection
        SelectionBackground = '#60A5FA'  # Lighter blue for dark theme
        SelectionFg = '#0F172A'
        FindHighlight = '#38BDF8'
        TextHighlight = '#3B82F6'     # Blue text selection
        TextHighlightFg = '#FFFFFF'
        SelectedTabBg = '#334155'
        TabHoverBg = '#334155'
        ErrorText = '#F08080'
        WarningText = '#FFB366'
        SuccessText = '#90EE90'
        SelectionTextBrush = '#FFFFFF'
        Link = '#FFFFFF'
    }

    # Bespin: Warm earth tones
    'Bespin' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#28211C'
        WindowFg = '#BAAE9E'
        ControlBg = '#36312C'
        ControlFg = '#BAAE9E'
        ButtonBg = '#4A433C'
        ButtonFg = '#BAAE9E'
        ButtonHover = '#5C544C'
        Border = '#5E5549'
        GroupBoxBg = '#2A241F'
        GroupBoxBorder = '#5E5549'
        Accent = '#CF6A4C'           # Copper/orange
        HeaderBackground = '#1E1914'
        HeaderForeground = '#BAAE9E'
        AccentHeaderBg = '#CF6A4C'
        AccentHeaderFg = '#28211C'
        Success = '#54BE0D'
        Warning = '#F9EE98'
        Error = '#CF6A4C'
        GridAlt = '#2A241F'
        GridLine = '#4A433C'          # Subtle grid line separator
        Disabled = '#6E6559'
        SecondaryText = '#8A7E72'
        ItemHover = '#3E3530'         # Subtle hover
        Selection = '#CF6A4C'         # Accent = Selection
        SelectionBackground = '#E8927A'  # Lighter copper for dark theme
        SelectionFg = '#1E1914'
        FindHighlight = '#F9EE98'
        TextHighlight = '#CF6A4C'     # Copper text selection
        TextHighlightFg = '#FFFFFF'
        SelectedTabBg = '#36312C'
        TabHoverBg = '#36312C'
        ErrorText = '#F08080'
        WarningText = '#FFB366'
        SuccessText = '#90EE90'
        SelectionTextBrush = '#000000'
        Link = '#F9EE98'
    }

    # Solarized Dark
    'SolarizedDark' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#002B36'
        WindowFg = '#93A1A1'
        ControlBg = '#073642'
        ControlFg = '#93A1A1'
        ButtonBg = '#073642'
        ButtonFg = '#EEE8D5'
        ButtonHover = '#0A4A5C'
        Border = '#586E75'
        GroupBoxBg = '#073642'
        GroupBoxBorder = '#586E75'
        Accent = '#2AA198'
        HeaderBackground = '#073642'
        HeaderForeground = '#93A1A1'
        AccentHeaderBg = '#268BD2'
        AccentHeaderFg = '#FDF6E3'
        Success = '#859900'
        Warning = '#B58900'
        Error = '#DC322F'
        GridAlt = '#003540'
        GridLine = '#094852'          # Subtle grid line separator
        Disabled = '#586E75'
        SecondaryText = '#657B83'
        ItemHover = '#094852'         # Subtle hover
        Selection = '#2AA198'         # Accent = Selection
        SelectionBackground = '#5DBDB5'  # Lighter cyan for dark theme
        SelectionFg = '#002B36'
        FindHighlight = '#B58900'
        TextHighlight = '#268BD2'
        TextHighlightFg = '#FDF6E3'
        SelectedTabBg = '#0A4A5C'
        TabHoverBg = '#0A4A5C'
        ErrorText = '#DC322F'
        WarningText = '#CB4B16'
        SuccessText = '#859900'
        SelectionTextBrush = '#FFFFFF'
        Link = '#EEE8D5'
    }

    # Charcoal: Neutral, Professional (VS Code style)
    'Charcoal' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#181818'
        WindowFg = '#CCCCCC'
        ControlBg = '#1F1F1F'
        ControlFg = '#CCCCCC'
        ButtonBg = '#313131'
        ButtonFg = '#FFFFFF'
        ButtonHover = '#3C3C3C'
        Border = '#454545'
        GroupBoxBg = '#1C1C1C'
        GroupBoxBorder = '#333333'
        Accent = '#0078D4'           # VS Code blue
        HeaderBackground = '#111111'
        HeaderForeground = '#E0E0E0'
        AccentHeaderBg = '#0078D4'
        AccentHeaderFg = '#FFFFFF'
        Success = '#89D185'
        Warning = '#DCDCAA'
        Error = '#F14C4C'
        GridAlt = '#1A1A1A'
        GridLine = '#333333'          # Subtle grid line separator
        Disabled = '#6E6E6E'
        SecondaryText = '#969696'
        ItemHover = '#2A2A2A'         # Subtle hover
        Selection = '#0078D4'         # Accent = Selection
        SelectionBackground = '#3AA0F0'  # Lighter blue for dark theme
        SelectionFg = '#111111'
        FindHighlight = '#DCDCAA'
        TextHighlight = '#264F78'     # VS Code blue text selection
        TextHighlightFg = '#FFFFFF'
        SelectedTabBg = '#2D2D2D'
        TabHoverBg = '#2D2D2D'
        ErrorText = '#F08080'
        WarningText = '#FFB366'
        SuccessText = '#90EE90'
        SelectionTextBrush = '#FFFFFF'
        Link = '#FFFFFF'
    }

    # DeepRed: Sophisticated dark with elegant crimson accents
    'DeepRed' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#1A1418'
        WindowFg = '#E8E4E6'
        ControlBg = '#252023'
        ControlFg = '#E8E4E6'
        ButtonBg = '#322A2E'
        ButtonFg = '#FFFFFF'
        ButtonHover = '#3E353A'
        Border = '#443A3F'
        GroupBoxBg = '#1F1A1D'
        GroupBoxBorder = '#443A3F'
        Accent = '#C41E3A'            # Cardinal crimson red
        HeaderBackground = '#252023'
        HeaderForeground = '#E8E4E6'
        AccentHeaderBg = '#A91B2E'
        AccentHeaderFg = '#FFFFFF'
        Success = '#7ECA9C'
        Warning = '#FFB86C'
        Error = '#E74C3C'
        GridAlt = '#221D20'
        GridLine = '#3E353A'          # Subtle grid line separator
        Disabled = '#6B5F64'
        SecondaryText = '#A89CA1'
        ItemHover = '#2D2329'         # Subtle hover
        Selection = '#C41E3A'         # Accent = Selection
        SelectionBackground = '#E85A6F'  # Lighter crimson for dark theme
        SelectionFg = '#FFFFFF'
        FindHighlight = '#7ECFC0'
        TextHighlight = '#A91B2E'     # Crimson text selection
        TextHighlightFg = '#FFFFFF'
        SelectedTabBg = '#322A2E'
        TabHoverBg = '#322A2E'
        ErrorText = '#FF6B6B'
        WarningText = '#FFB86C'
        SuccessText = '#7ECA9C'
        SelectionTextBrush = '#FFFFFF'
        Link = '#FFFFFF'
    }

    # Monokai: Classic dark theme
    'Monokai' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#272822'
        WindowFg = '#F8F8F2'
        ControlBg = '#1E1F1A'
        ControlFg = '#F8F8F2'
        ButtonBg = '#3E3D32'
        ButtonFg = '#F8F8F2'
        ButtonHover = '#49483E'
        Border = '#49483E'
        GroupBoxBg = '#23241F'
        GroupBoxBorder = '#3E3D32'
        Accent = '#F92672'
        HeaderBackground = '#1E1F1A'
        HeaderForeground = '#F8F8F2'
        AccentHeaderBg = '#F92672'
        AccentHeaderFg = '#FFFFFF'
        Success = '#A6E22E'
        Warning = '#E6DB74'
        Error = '#F92672'
        GridAlt = '#1E1F1A'
        GridLine = '#3E3D32'          # Subtle grid line separator
        Disabled = '#75715E'
        SecondaryText = '#75715E'
        ItemHover = '#3E3D32'
        Selection = '#FF85A2'         # Lighter pink (original)
        SelectionBackground = '#FF85A2'  # Pink selection background
        SelectionFg = '#272822'
        FindHighlight = '#E6DB74'
        TextHighlight = '#49483E'
        TextHighlightFg = '#F8F8F2'
        SelectedTabBg = '#3E3D32'
        TabHoverBg = '#3E3D32'
        ErrorText = '#F92672'
        WarningText = '#FD971F'
        SuccessText = '#A6E22E'
        SelectionTextBrush = '#FFFFFF'
        Link = '#F8F8F2'
    }

    # Lavender: Soft purple tones with violet accents
    'Lavender' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#F8F5FC'
        WindowFg = '#3D3455'
        ControlBg = '#FFFFFF'
        ControlFg = '#3D3455'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#3D3455'
        ButtonHover = '#EDE8F5'
        Border = '#D4CCE5'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#E5DFF0'
        Accent = '#7C3AED'            # Vibrant violet
        HeaderBackground = '#EDE8F5'
        HeaderForeground = '#3D3455'
        AccentHeaderBg = '#7C3AED'
        AccentHeaderFg = '#FFFFFF'
        Success = '#10B981'
        Warning = '#F59E0B'
        Error = '#EF4444'
        GridAlt = '#FAF8FD'
        GridLine = '#E5DFF0'          # Subtle grid line separator
        Disabled = '#A8A0B8'
        SecondaryText = '#6B5F7D'
        ItemHover = '#F3EEFA'         # Subtle violet hover
        Selection = '#7C3AED'
        SelectionBackground = '#5B21B6'  # Darker violet for selection
        SelectionFg = '#FFFFFF'
        FindHighlight = '#FCD34D'
        TextHighlight = '#DDD6FE'     # Light violet text selection
        TextHighlightFg = '#3D1F6D'
        SelectedTabBg = '#EDE8F5'
        TabHoverBg = '#EDE8F5'
        ErrorText = '#DC2626'
        WarningText = '#D97706'
        SuccessText = '#059669'
        SelectionTextBrush = '#FFFFFF'
        Link = '#6D28D9'
    }

    # Pearl: Luxurious warm cream with rose gold accent
    'Pearl' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#FDFBF9'
        WindowFg = '#3D3835'
        ControlBg = '#F5F0EB'
        ControlFg = '#3D3835'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#3D3835'
        ButtonHover = '#F5F0EB'
        Border = '#E5DED6'
        GroupBoxBg = '#FAF7F4'
        GroupBoxBorder = '#E5DED6'
        Accent = '#B76E79'            # Rose gold
        HeaderBackground = '#F5F0EB'
        HeaderForeground = '#3D3835'
        AccentHeaderBg = '#B76E79'
        AccentHeaderFg = '#FFFFFF'
        Success = '#739E73'
        Warning = '#D4A574'
        Error = '#C97878'
        GridAlt = '#FAF7F4'
        GridLine = '#E5DED6'          # Subtle grid line separator
        Disabled = '#B8B0A8'
        SecondaryText = '#7A716A'
        ItemHover = '#F8F0F1'         # Subtle hover
        Selection = '#B76E79'         # Accent = Selection
        SelectionBackground = '#9A5561'  # Darker rose for light theme
        SelectionFg = '#FFFFFF'
        FindHighlight = '#D4A574'
        TextHighlight = '#EACDD1'     # Light rose text selection
        TextHighlightFg = '#4A2930'
        SelectedTabBg = '#F5E8EA'
        TabHoverBg = '#F5E8EA'
        ErrorText = '#C97878'
        WarningText = '#D4A574'
        SuccessText = '#739E73'
        SelectionTextBrush = '#000000'
        Link = '#7B5C9E'
    }

    # Slate: Professional blue-gray enterprise theme
    'Slate' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#F8FAFC'
        WindowFg = '#1E293B'
        ControlBg = '#FFFFFF'
        ControlFg = '#1E293B'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#334155'
        ButtonHover = '#F1F5F9'
        Border = '#CBD5E1'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#E2E8F0'
        Accent = '#475569'            # Slate gray-blue
        HeaderBackground = '#F1F5F9'
        HeaderForeground = '#1E293B'
        AccentHeaderBg = '#475569'
        AccentHeaderFg = '#FFFFFF'
        Success = '#059669'
        Warning = '#D97706'
        Error = '#DC2626'
        GridAlt = '#F8FAFC'
        GridLine = '#E2E8F0'          # Subtle grid line separator
        Disabled = '#94A3B8'
        SecondaryText = '#64748B'
        ItemHover = '#F1F5F9'         # Subtle slate hover
        Selection = '#475569'         # Accent = Selection
        SelectionBackground = '#334155'  # Darker slate for selection
        SelectionFg = '#FFFFFF'
        FindHighlight = '#FCD34D'
        TextHighlight = '#CBD5E1'     # Light slate text selection
        TextHighlightFg = '#1E293B'
        SelectedTabBg = '#E2E8F0'
        TabHoverBg = '#E2E8F0'
        ErrorText = '#DC2626'
        WarningText = '#D97706'
        SuccessText = '#059669'
        SelectionTextBrush = '#FFFFFF'
        Link = '#2563EB'
    }

    # Sage: Calm professional green-tinted theme
    'Sage' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#F7FAF8'
        WindowFg = '#1F2A24'
        ControlBg = '#FFFFFF'
        ControlFg = '#1F2A24'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#2D3E33'
        ButtonHover = '#EEF4F0'
        Border = '#C8D9CE'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#DCE8E0'
        Accent = '#4A7C59'            # Forest sage green
        HeaderBackground = '#EEF4F0'
        HeaderForeground = '#1F2A24'
        AccentHeaderBg = '#4A7C59'
        AccentHeaderFg = '#FFFFFF'
        Success = '#3D8B4F'
        Warning = '#C17F24'
        Error = '#C2433A'
        GridAlt = '#F7FAF8'
        GridLine = '#DCE8E0'          # Subtle grid line separator
        Disabled = '#9CB3A4'
        SecondaryText = '#5B7562'
        ItemHover = '#EEF4F0'         # Subtle sage hover
        Selection = '#4A7C59'         # Accent = Selection
        SelectionBackground = '#3A6347'  # Darker sage for selection
        SelectionFg = '#FFFFFF'
        FindHighlight = '#E8C547'
        TextHighlight = '#C8E0CE'     # Light sage text selection
        TextHighlightFg = '#1F3527'
        SelectedTabBg = '#E2EDE6'
        TabHoverBg = '#E2EDE6'
        ErrorText = '#C2433A'
        WarningText = '#C17F24'
        SuccessText = '#3D8B4F'
        SelectionTextBrush = '#FFFFFF'
        Link = '#2E6B5A'
    }

    # Solarized Light
    'SolarizedLight' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#FDF6E3'
        WindowFg = '#657B83'
        ControlBg = '#EEE8D5'
        ControlFg = '#657B83'
        ButtonBg = '#EEE8D5'
        ButtonFg = '#586E75'
        ButtonHover = '#E4DCCA'
        Border = '#93A1A1'
        GroupBoxBg = '#FDF6E3'
        GroupBoxBorder = '#93A1A1'
        Accent = '#268BD2'
        HeaderBackground = '#EEE8D5'
        HeaderForeground = '#586E75'
        AccentHeaderBg = '#268BD2'
        AccentHeaderFg = '#FDF6E3'
        Success = '#859900'
        Warning = '#B58900'
        Error = '#DC322F'
        GridAlt = '#EEE8D5'
        GridLine = '#C9C2B0'          # Subtle grid line separator
        Disabled = '#93A1A1'
        SecondaryText = '#839496'
        ItemHover = '#E4DCCA'         # Subtle cream hover
        Selection = '#268BD2'         # Accent = Selection
        SelectionBackground = '#2075B0'  # Darker blue for selection
        SelectionFg = '#FDF6E3'
        FindHighlight = '#B58900'
        TextHighlight = '#D3E5F3'
        TextHighlightFg = '#073642'
        SelectedTabBg = '#E4DCCA'
        TabHoverBg = '#E4DCCA'
        ErrorText = '#DC322F'
        WarningText = '#CB4B16'
        SuccessText = '#859900'
        SelectionTextBrush = '#FFFFFF'
        Link = '#268BD2'
    }

    # Evergreen: Nature-inspired dark with soft green accents
    'Evergreen' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#2B3339'
        WindowFg = '#D3C6AA'
        ControlBg = '#323D43'
        ControlFg = '#D3C6AA'
        ButtonBg = '#3D4A50'
        ButtonFg = '#E0D6C2'
        ButtonHover = '#475258'
        Border = '#4F585E'
        GroupBoxBg = '#2F3A3F'
        GroupBoxBorder = '#4A5258'
        Accent = '#A7C080'            # Soft sage green
        HeaderBackground = '#272E33'
        HeaderForeground = '#D3C6AA'
        AccentHeaderBg = '#A7C080'
        AccentHeaderFg = '#2B3339'
        Success = '#A7C080'
        Warning = '#DBBC7F'
        Error = '#E67E80'
        GridAlt = '#2E383E'
        GridLine = '#4A5258'          # Subtle grid line separator
        Disabled = '#6B7B7D'
        SecondaryText = '#9DA9A0'
        ItemHover = '#3A4248'
        Selection = '#A7C080'
        SelectionBackground = '#8CAA68'
        SelectionFg = '#232A2E'
        FindHighlight = '#DBBC7F'
        TextHighlight = '#4A5D3A'
        TextHighlightFg = '#D3C6AA'
        SelectedTabBg = '#3A4248'
        TabHoverBg = '#3A4248'
        ErrorText = '#E67E80'
        WarningText = '#DBBC7F'
        SuccessText = '#A7C080'
        SelectionTextBrush = '#000000'
        Link = '#7FBBB3'
    }

    # Midnight: Deep purple-blue with lavender text (Catppuccin Mocha inspired)
    'Midnight' = @{
        Type = 'Dark'
        DisabledOpacity = 0.35
        WindowBg = '#1E1E2E'
        WindowFg = '#CDD6F4'
        ControlBg = '#313244'
        ControlFg = '#CDD6F4'
        ButtonBg = '#45475A'
        ButtonFg = '#CDD6F4'
        ButtonHover = '#585B70'
        Border = '#6C7086'
        GroupBoxBg = '#1E1E2E'
        GroupBoxBorder = '#45475A'
        Accent = '#89B4FA'            # Soft blue
        HeaderBackground = '#181825'
        HeaderForeground = '#CDD6F4'
        AccentHeaderBg = '#89B4FA'
        AccentHeaderFg = '#1E1E2E'
        Success = '#A6E3A1'
        Warning = '#F9E2AF'
        Error = '#F38BA8'
        GridAlt = '#181825'
        GridLine = '#45475A'          # Subtle grid line separator
        Disabled = '#6C7086'
        SecondaryText = '#A6ADC8'
        ItemHover = '#45475A'
        Selection = '#89B4FA'
        SelectionBackground = '#89B4FA'
        SelectionFg = '#1E1E2E'
        FindHighlight = '#F9E2AF'
        TextHighlight = '#89B4FA'
        TextHighlightFg = '#1E1E2E'
        SelectedTabBg = '#45475A'
        TabHoverBg = '#45475A'
        ErrorText = '#F38BA8'
        WarningText = '#F9E2AF'
        SuccessText = '#A6E3A1'
        SelectionTextBrush = '#000000'
        Link = '#89DCEB'
    }

    # Frost: Crisp arctic theme with icy blue accents
    'Frost' = @{
        Type = 'Light'
        DisabledOpacity = 0.2
        WindowBg = '#F0F4F8'
        WindowFg = '#2D3748'
        ControlBg = '#FFFFFF'
        ControlFg = '#2D3748'
        ButtonBg = '#FFFFFF'
        ButtonFg = '#2D3748'
        ButtonHover = '#E2E8F0'
        Border = '#CBD5E0'
        GroupBoxBg = '#FFFFFF'
        GroupBoxBorder = '#E2E8F0'
        Accent = '#4299E1'            # Icy blue
        HeaderBackground = '#E2E8F0'
        HeaderForeground = '#2D3748'
        AccentHeaderBg = '#4299E1'
        AccentHeaderFg = '#FFFFFF'
        Success = '#48BB78'
        Warning = '#ED8936'
        Error = '#F56565'
        GridAlt = '#F7FAFC'
        GridLine = '#E2E8F0'          # Subtle grid line separator
        Disabled = '#A0AEC0'
        SecondaryText = '#718096'
        ItemHover = '#EBF4FF'         # Subtle icy hover
        Selection = '#4299E1'
        SelectionBackground = '#2B6CB0'  # Darker blue for selection
        SelectionFg = '#FFFFFF'
        FindHighlight = '#F6E05E'
        TextHighlight = '#BEE3F8'     # Light icy blue selection
        TextHighlightFg = '#2A4365'
        SelectedTabBg = '#E1EEFA'
        TabHoverBg = '#E1EEFA'
        ErrorText = '#E53E3E'
        WarningText = '#DD6B20'
        SuccessText = '#38A169'
        SelectionTextBrush = '#000000'
        Link = '#3182CE'
    }
}

# Default theme 'Light' is set in ModuleContext.cs - no need to set here
# (Setting here would reset user's theme when module is imported into async runspaces)

