name: Pester Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Pester Tests
        shell: pwsh
        run: |
          $result = Invoke-Pester .\Tests\PsUi.Tests.ps1 -Output Detailed -PassThru
          if ($result.FailedCount -gt 0) { exit 1 }
